import strim from "./index.js"

const baz = `
    # This script has been auto-generated by the 'demo' application
      # The generation source can be found at '/some/path/app/config.js'

`

const foo = `

        #!/bin/bash

        # This script has been auto-generated by the 'demo' application
          # The generation source can be found at '/some/path/app/config.js'



        # Application can not operate on files outside its ownership or realm.
                # If Certbot saves certificates at its default --config-dir (/etc/letsencrypt) then copy and give them appropriate file execution permissions.
`

const blib = `
    openssl
    x509
    -inform PEM
    -in "cert.pem"
    -outform DER
    -out "cert.der"
`

const foobar = `
    # Application can not operate on files outside its ownership or realm.
    # If Certbot saves certificates at its default --config-dir (/etc/letsencrypt) then copy and give them appropriate file execution permissions.

    OG_KEY="\${join("/etc/letsencrypt/live", HOST_ALIAS, basename(SSL_CREDENTIALS.letsencrypt.key))}"
    OG_CERT="\${join("/etc/letsencrypt/live", HOST_ALIAS, basename(SSL_CREDENTIALS.letsencrypt.cert))}"
    KEY="\${SSL_CREDENTIALS.letsencrypt.key}"
    CERT="\${SSL_CREDENTIALS.letsencrypt.cert}"

    if [ -e $OG_KEY ] && [ -e $OG_CERT ]; then
        cp $OG_KEY $KEY
        cp $OG_CERT $CERT
        chmod \${FILE_PERMISSIONS.toString(8)} $KEY
        chmod \${FILE_PERMISSIONS.toString(8)} $CERT
    fi
`

console.log(
    strim(
        //baz
        //foobar
        blib, true
    )
)

/*
console.log(
    strim(`

                #!/bin/bash


            
                a

                # This script has been auto-generated by the 'demo' application
                    # The generation source can be found at '/some/path/app/config.js'

                # Application can not operate on files outside its ownership or realm.
                        # If Certbot saves certificates at its default --config-dir (/etc/letsencrypt) then copy and give them appropriate file execution permissions.
`, true))
*/