import strim from "./index.js"

console.log(strim(`
            #!/bin/bash

            # This script has been auto-generated by the 'demo' application
            # The generation source can be found at '/some/path/app/config.js'

            # Application can not operate on files outside its ownership or realm.
            # If Certbot saves certificates at its default --config-dir (/etc/letsencrypt) then copy and give them appropriate file execution permissions.
`))